jenkins:
    systemMessage: "Amazon Fargate Jenkins Server"
    numExecutors: 0
    remotingSecurity:
      enabled: true
    agentProtocols:
        - "JNLP4-connect"
    securityRealm:
        local:
            allowsSignup: false
            users:
                - id: ecsuser
                  password: ${JENKINS_ADMIN_PWD}
    authorizationStrategy:
        globalMatrix:
            grantedPermissions:
                - "Overall/Read:authenticated"
                - "Job/Read:authenticated"
                - "View/Read:authenticated"
                - "Overall/Administer:authenticated"
    crumbIssuer: "standard"
    slaveAgentPort: 50000
    clouds:
        - ecs:
              numExecutors: 1
              allowedOverrides: "inheritFrom,label,memory,cpu,image"
              credentialsId: ""
              cluster: "arn:aws:ecs:us-east-1:890218635137:cluster/afg-jenkins-worker-cluster"
              name: "fargate-worker-cloud"
              regionName: "us-east-1"
              retentionTimeout: 10
              jenkinsUrl: "https://jenkins-mig.tronixtrm.com"
              templates:
                  - cpu: "512"
                    image: "jenkins/inbound-agent"
                    label: "fargate-worker-cloud"
                    assignPublicIp: false
                    platformVersion: "1.4.0"
                    executionRole: "arn:aws:iam::890218635137:role/afg-afg-task-jenkins-task-execution-role"
                    taskrole: "arn:aws:iam::890218635137:role/afg-afg-task-jenkins-task-role"
                    launchType: "FARGATE"
                    memory: 0
                    memoryReservation: 1024
                    networkMode: "awsvpc"
                    privileged: false
                    remoteFSRoot: "/home/jenkins"
                    securityGroups: "sg-0dba5e6bdc01c1141"
                    sharedMemorySize: 0
                    containerUser: root
                    subnets: "subnet-07711725f6ade72e6,subnet-0552d2d2da68a8386"
                    templateName: "default"
                    uniqueRemoteFSRoot: false
                    logDriver: "awslogs"
                    environments:
                      - name: "JENKINS_WEB_SOCKET"
                        value: "true"
                    logDriverOptions:
                      - name: "awslogs-region"
                        value: "us-east-1"
                      - name: "awslogs-group"
                        value: "afg-log-grp-jenkins-20240806182731548800000001"
                      - name: "awslogs-stream-prefix"
                        value: "afg-log-grp-jenkins-log_stream"
        
security:
  sSHD:
    port: -1
jobs:
  
  - script: >
      pipelineJob('Simple job non critical task') {
        definition {
          cps {
            script('''
              pipeline {
                  agent {
                      ecs {
                          inheritFrom 'fargate-worker-cloud'
                      }
                  }
                  stages {
                    stage('Test') {
                        steps {
                            script {
                                sh "echo this was executed on a fargate worker cloud"
                            }
                            sh 'sleep 120'
                            sh 'echo sleep is done'
                        }
                    }
                  }
              }'''.stripIndent())
              sandbox()
          }
        }
      }
